version: "3.8"

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: case_study
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  scraper:
    build: .
    depends_on:
      - postgres
    restart: always
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
